[package]
name = "rbt"
version = "0.1.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = {git = "https://github.com/rust-bio/rust-bio.git"}
clap = {version = "2", features = ["yaml", "color", "suggestions"]}
itertools = "0.4.*"
log = "0.3.*"
fern = "0.3.*"
rust-htslib = "0.6.*"
csv = "0.14.*"
rustc-serialize = "0.3.*"
